include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    # Don't analyze generated sources and tests.
    - api/*
    - test/*
    - "build/**"
    - "**.g.dart"
    - 'packages/sse_client/test/**'
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  page_width: 100
  trailing_commas: preserve

linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    # sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    # prefer_double_quotes: true

    # Good packages document everything
    # public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    # always_specify_types: true
    avoid_types_on_closure_parameters: true
    omit_local_variable_types: true

    # Back to the 80s
    # lines_longer_than_80_chars: true

    # Always use curly braces in if-else statements
    curly_braces_in_flow_control_structures: true

    # Use lowerCamelCase for constant variables
    constant_identifier_names: true

    # Use lowerCamelCase for non-constant
    non_constant_identifier_names: true

    # Do not use BuildContext in async code
    use_build_context_synchronously: false

    depend_on_referenced_packages: false
    sort_pub_dependencies: false
    unawaited_futures: true
    discarded_futures: true
